name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install flet flet-cli --break-system-packages
      - run: flet build ios --org com.res18dprch.player --yes --release
      - name: Create IPA
        run: |
          # Прямая упаковка без лишних папок
          mkdir -p Payload
          find . -name "*.app" -exec cp -r {} Payload/ \;
          zip -vr manual_build.ipa Payload/
      - uses: actions/upload-artifact@v4
        with:
          name: APP_FINISHED
          path: manual_build.ipa
