name: Build IPA
on: [push]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install flet flet-cli --break-system-packages
      
      - name: Build Flet IPA
        run: flet build ipa --org com.res18dprch.player --yes

      - name: Patch and Zip
        run: |
          mkdir -p Payload
          cp -r build/ipa/*.app Payload/
          
          # Прямые команды без поиска - так надежнее
          APP_PATH="Payload/*.app"
          /usr/libexec/PlistBuddy -c "Add :UIFileSharingEnabled bool true" $APP_PATH/Info.plist
          /usr/libexec/PlistBuddy -c "Add :LSSupportsOpeningDocumentsInPlace bool true" $APP_PATH/Info.plist
          /usr/libexec/PlistBuddy -c "Add :UIBackgroundModes array" $APP_PATH/Info.plist
          /usr/libexec/PlistBuddy -c "Add :UIBackgroundModes:0 string audio" $APP_PATH/Info.plist
          
          zip -r audio_node_final.ipa Payload/

      - uses: actions/upload-artifact@v4
        with:
          name: APP_STABLE
          path: audio_node_final.ipa
